name: Publish npm package

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    outputs:
      version:
        description: 'The latest app version in `package.json`'
        value: ${{ jobs.publish.outputs.version }}

  workflow_dispatch:
    inputs:
      tag:
        description: 'The NPM version tag to use, "latest" will become the default package version, or "prerelease"'
        required: true
        default: 'latest'

permissions:
  contents: write # for git push prerelease version bump
  id-token: write # for npm trusted publishing

jobs:
  publish:
    name: Build package and publish to npm
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.app_version.outputs.version }}
    steps:
      - uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn

      - id: build
        name: Install dependencies, and build
        run: |
          yarn install --silent --inline-builds --no-immutable
          yarn run build

      - id: bump_prerelease
        name: Increment prerelease package version and rebuild package
        if: inputs.tag == 'prerelease' && !contains(github.event.head_commit.message, '[nopublish]')
        run: |
          cd packages/contensis-cli
          npm version prerelease --preid=beta --no-git-tag-version
          npm run build

      - id: app_version
        name: Set APP_VERSION output variable
        run: |
          APP_VERSION=$(node --eval="process.stdout.write(require('./packages/contensis-cli/package.json').version)")
          echo "version=$APP_VERSION"
          echo "version=$APP_VERSION" >> $GITHUB_OUTPUT

      - id: push_prerelease
        name: Push prerelease version increment to GIT
        if: inputs.tag == 'prerelease' && !contains(github.event.head_commit.message, '[nopublish]')
        run: |
          git config user.email "github@zengenti.com"
          git config user.name "$GITHUB_ACTOR"
          git add packages/contensis-cli/.
          git commit -m "ci: bumps prerelease version to ${{ steps.app_version.outputs.version }} [skip ci]"
          git push
        env:
          # The secret is passed automatically. Nothing to configure.
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - id: publish
        name: Publish to npm
        if: contains(github.event.head_commit.message, '[nopublish]') == false
        run: npm publish --tag ${{ inputs.tag }} --ignore-scripts --access public --workspace contensis-cli
